import Head from "next/head";
import Image from "next/image";
import QuestCards from "../../components/QuestCards";
import styles from "../../styles/Home.module.css";
// import styles from "../../styles/Home.module.css";
// import styles from "../styles/Home.module.css";
import { Quest } from "../../types/index";
import questData from "../../quests/quests";
import { getJourneys } from "../../quests/questData";
import { GetStaticPaths, GetStaticProps } from "next";
import { Params } from "next/dist/server/router";

// interface Props {
//   quest: Quest;
// }

export default function QuestPage({ getQuestData }) {
  const quest = getQuestData;

  const headContent = (
    <Head>
      <title>{quest.id}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );

  const questContent = (
    <div className="grid grid-cols-2 gap-4 md:grid-cols-3 ">
      {questData.map((e: Quest, i) => {
        return <QuestCards key={i} questData={e} />;
      })}
    </div>
  );

  const footerContent = (
    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{" "}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
  );

  const introductionContent = () => {
    return (
      <div className="flex w-full items-center">
        <div className="w-1/3 h-48 flex justify-center self-center">
          <iframe
            className="rounded-xl"
            src="https://www.youtube.com/embed/E7wJTI-1dvQ"
            frameBorder="0"
            allow="autoplay; encrypted-media"
            allowFullScreen
            title="video"
          />
        </div>
        <div className="w-1/3 h-48 flex justify-center self-center">
          <iframe
            className="rounded-xl"
            src="https://www.youtube.com/embed/E7wJTI-1dvQ"
            frameBorder="0"
            allow="autoplay; encrypted-media"
            allowFullScreen
            title="video"
          />
        </div>
        <div className="w-1/3 h-48 flex justify-center self-center">
          <iframe
            className="rounded-xl"
            src="https://www.youtube.com/embed/E7wJTI-1dvQ"
            frameBorder="0"
            allow="autoplay; encrypted-media"
            allowFullScreen
            title="video"
          />
        </div>
      </div>
    );
  };

  const mainQuestContent = () => {
    console.log(quest.tasks);
    if (!quest.tasks) {
      return;
    }
    return (
      <div className="flex flex-row flex-wrap w-5/6">
        {quest.tasks.map((e, i) => {
          return (
            <div
              key={i}
              className="flex flex-col rounded-2xl h-1/2 w-1/3 my-8 bg-red-400"
            >
              <h1>{e.name}</h1>
              <p>{e.description}</p>
              <p>{e.points}</p>
            </div>
          );
        })}
      </div>
    );
  };

  const questDescriptionContent = (
    <div className="flex flex-row item-start">
      <div className="flex flex-column">
        {/* <div className="max-w-[50%]"> */}
        <div>
          {/* <div style={{ height: 250, width: 250, background: "gray" }} /> */}
          <h1 className="text-6xl">{quest.id}</h1>
          <p className="py-6 text-xl text-slate-500">{quest.description}</p>
        </div>
      </div>
    </div>
  );

  return (
    <div className={styles.container}>
      {headContent}
      <main className={styles.main}>
        {questDescriptionContent}
        {mainQuestContent()}
      </main>
      {footerContent}
    </div>
  );
}

export const getStaticPaths: GetStaticPaths = async () => {
  const getJourneysData = getJourneys();
  return {
    paths: getJourneysData.map((i) => {
      return { params: { quest: i.id } };
    }),
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const journeyName = context.params?.quest;
  if (!journeyName) {
    return {
      props: null,
      notFound: true,
    };
  }

  const getQuestData = getJourneys().find(
    (i) => i.id.toLowerCase() === journeyName.toLowerCase()
  );
  if (!getQuestData) {
    return {
      props: null,
      notFound: true,
    };
  }
  return {
    props: {
      getQuestData,
    },
    revalidate: 3600,
  };
};
