import Head from "next/head";
import Image from "next/image";
import QuestCards from "../components/questCards";
import styles from "../styles/Home.module.css";
// import styles from "../../styles/Home.module.css";
// import styles from "../styles/Home.module.css";
import { Quest } from "../types/index";
import questData from "../quests/quests";
import { getQuestNames, getJourneys } from "../quests/questData";
import Header from "../components/header";
import Link from "next/link";

export default function Home({ getJourneysData }) {
  const headContent = (
    <Head>
      <title>lil pragma</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );

  const questContent = (enabledQuest: boolean) => {
    return (
      <div className="grid grid-cols-2 xs:gap-6 lg:gap-12 lg:grid-cols-3 ">
        {getJourneysData.map((e: Quest, i) => {
          // console.log(e);
          if (enabledQuest) {
            // if (enabledQuest) {
            <QuestCards key={i} questData={e} />;
            return <QuestCards key={i} questData={e} />;
          } else {
            return null;
          }
          // return <QuestCards key={i} questData={e} />;
        })}
      </div>
    );
  };

  const footerContent = (
    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{" "}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
  );

  return (
    <div className={styles.container}>
      <h1 className="text-4xl text-center">lil pragma</h1>
      <p className="py-6 text-xl text-center text-slate-500">
        smoll web3 projects with a lil dev score
      </p>
      {/* <Link href="/ethos" passHref>
        <p className="py-4 underline text-center text-slate-500">manifesto</p>
      </Link> */}
      {questContent(true)}
    </div>
  );
}

export async function getStaticProps() {
  const getJourneysData = getJourneys();

  return {
    props: {
      getJourneysData,
    },
  };
}
