import React from "react";
import NextLink from "next/link";
import Head from "next/head";
import Wallet from "./wallet";
// import journey from "pages/api/journey";

export default function Header() {
  return (
    <Head>
      <title>lil pragma</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta property="og:image" content="/openGraph.png" />
      <Wallet />
    </Head>
  );
}
